### ISSUE TITLE
Cannot read property 'package' of null

### ISSUE THREAD

**Issue by jessehattabaugh** [mischnic/parcel-plugin-sw-cache#12]
I get an error when I bundle:
```
Cannot read property 'package' of null
    at Bundler.bundler.on.bundle (C:\Users\me\node_modules\parcel-plugin-sw-cache\index.js:30:54)
```
coming from [this line](https://github.com/mischnic/parcel-plugin-sw-cache/blob/master/index.js#L30)

I tried adding the `cache` property to my package.json. but it didn't help.

I'm on Windows 10, the error occurs in PowerShell and WSL Ubuntu Bash

**Comment by jessehattabaugh** [comment]
I tried uncommenting the line above, and commenting out the line with the error and it works fine now.

**Comment by jessehattabaugh** [comment]
Parcel 1.9.7
Node 10.9.0

**Comment by mischnic** [comment]
The only message I get with the included example and Parcel 1.9.7 is: `asset.package` is deprecated. Please use `await asset.getPackage()` instead.`.

**Comment by jessehattabaugh** [comment]
I don't get that message

**Comment by jessehattabaugh** [comment]
Any idea when you'll have time to fix this?

**Comment by mischnic** [comment]
> Any idea when you'll have time to fix this?

I can't reproduce it (yet). Which version of `parcel-plugin-sw-cache` do you have installed? (Latest is v0.2.5).

Could you please insert this: `console.log(bundle.entryAsset);` before the line where the error happens and post the output?

Do you get this error with the included example? (Clone parcel-plugin-sw-cache, run `npm i` or `yarn` inside the example folder and run the `start` or `build` script.

**Comment by jessehattabaugh** [comment]
I am using "parcel-plugin-sw-cache": "^0.2.5".

console.log(bundle.entryAsset); outputs null

console.dir(bundle); outputs this; 

```
Bundle {
  type: undefined,
  name: undefined,
  parentBundle: undefined,
  entryAsset: null,
  assets: Set {},
  childBundles:
   Set {
     Bundle {
       type: 'html',
       name:
        'C:\\Users\\Jesse Hattabaugh\\jessehattabaugh-com\\dist\\index.html',
       parentBundle: [Circular],
       entryAsset: [HTMLAsset],
       assets: [Set],
       childBundles: [Set],
       siblingBundles: Set {},
       siblingBundlesMap: Map {},
       offsets: Map {},
       totalSize: 7858,
       bundleTime: 1784,
       isolated: undefined },
     Bundle {
       type: 'html',
       name:
        'C:\\Users\\Jesse Hattabaugh\\jessehattabaugh-com\\dist\\share.html',
       parentBundle: [Circular],
       entryAsset: [HTMLAsset],
       assets: [Set],
       childBundles: Set {},
       siblingBundles: Set {},
       siblingBundlesMap: Map {},
       offsets: Map {},
       totalSize: 2499,
       bundleTime: 1821,
       isolated: undefined } },
  siblingBundles: Set {},
  siblingBundlesMap: Map {},
  offsets: Map {},
  totalSize: 0,
  bundleTime: 0,
  isolated: undefined }
```
When I run `example` I get the error that you mentioned: `Parcel 1.9.7 is: asset.package is deprecated. Please use await asset.getPackage() instead.`

I notice that the example is using "parcel-bundler": "^1.9.0", "parcel-plugin-sw-cache": "^0.2.0"

**Comment by jessehattabaugh** [comment]
Yes, by build command is `parcel build src/*.html` and there are two .html files in `/src`. Is that not supported by this plugin?

**Comment by mischnic** [comment]
> Is that not supported by this plugin?

Please test with version 0.2.6.

**Comment by jessehattabaugh** [comment]
Woo hoo! Working fine! Much appreciated!
