### ISSUE TITLE
generateSW skipWaiting & clientsClaim

### ISSUE THREAD

**Issue by Hiswe** [mischnic/parcel-plugin-sw-cache#14]
Hi,

first thank you for this great plugin!

Second, is there a reason that you override some defaults of the [generatesw config](https://developers.google.com/web/tools/workbox/modules/workbox-build#full_generatesw_config) (`skipWaiting` & `clientsClaim`)?

I was expecting that the same default configuration was used by your code.
Nothing big though as it can be easily overriden in the `package.json`.

But IMO it should stick to the workbox default or at least mention any deviation from it in the README.md :)
In the first case, the update should be made in a major release…
In all cases I can make a PR if needed.

Anyway, thanks again for making/maintaining this!

**Comment by mischnic** [comment]
Thanks for bringing this up!
