### ISSUE TITLE
Inject Error – `No files match the pattern` for replace-in-file

### ISSUE THREAD

**Issue by Hiswe** [mischnic/parcel-plugin-sw-cache#15]
Hi,

me again,

I have this error while using the plugin in `inject` mode:

```
UnhandledPromiseRejectionWarning: Error: No files match the pattern: /Users/me/Documents/project/dist/thaime-service-worker.js
```
This seems to come from the [replace function](https://github.com/mischnic/parcel-plugin-sw-cache/blob/master/index.js#L93-L99) in the inject Promise chain.

Shouldn't it be:

```js
workbox
  .injectManifest(injectOptions)
  // return the promise
  .then(() =>
    replace({
      files: config.swDest || swDest,
      from: /__PUBLIC/g,
      to: publicURL,
    })
  )
  .then(() => printErr('sw-cache: Service worker injection completed.'))
  .catch(error =>
    printErr('sw-cache: Service worker injection failed: ' + error)
  )
```

If this is really an error, I can come with a PR :)

**Comment by mischnic** [comment]
> If this is really an error, I can come with a PR :)

I think you're right, please do 👍

**Comment by Hiswe** [comment]
done in #16

**Comment by Hiswe** [comment]
@mischnic Thanks for publishing the fix! It's all good now :)
