### ISSUE TITLE
Local source for workboxSW

### ISSUE THREAD

**Issue by goofblob** [mischnic/parcel-plugin-sw-cache#2]
Is it possible to configure the plugin to load workbox-sw.js from a local source, rather than the Google CDN? 

If not, it should be.

Say, the plug-in installs workbox-sw as a npm dependency, and at Parcel build time, it copies the production version of workbox-sw.js from its local node_modules folder, places it in /dist/ and sw.js does only 

> importScript('workbox-sw.js')

For one of my projects, getting workbox from the Google CDN takes longer than not using a service worker at all.

Thanks.

**Comment by mischnic** [comment]
Actually, this is already possible:

`package.json`:
```json
{
  "name": "MyApp",
  "cache": {
    "importWorkboxFrom": "local"
  }
}
```

(The documentation at https://developers.google.com/web/tools/workbox/reference-docs/prerelease/module-workbox-build#.Configuration is misleading.)

![bildschirmfoto 2018-01-31 um 21 44 53](https://user-images.githubusercontent.com/4586894/35646624-0a7ee102-06d0-11e8-9788-37c06a501dbc.png)

**Comment by goofblob** [comment]
Amazing!

Thanks.
