### ISSUE TITLE
Add other file types in globPatterns

### ISSUE THREAD

**Issue by andredarcie** [mischnic/parcel-plugin-sw-cache#31]
How to add other types of files to globPatterns and change the default behavior?

Today the default cofiguration only supports this file types, how to chance and add sounds files like .wav and .mp3
`globPatterns: ["**/*.{html,js,css,jpg,png}"],`

**Comment by mischnic** [comment]
Specifying them in the `cache`  object in package.json should work
```js
{
    "dependencies": {
        // ...
    },
    //...
    "cache": {
		"swDest": "service-worker.js",
        "globPatterns": ["**/*.{html,js,css,jpg,png,wav.mp3}"]
    }
    //...
}
```

**Comment by andredarcie** [comment]
I added it to the _package.json_ file and now it works! Thank you!

```
  "cache": {
    "disablePlugin": false,
    "inDev": true,
    "strategy": "default",
    "importWorkboxFrom": "local",
    "globPatterns": [
      "**/*.{html,js,css,jpg,png,wav,mp3,mpeg,ttf}"
    ]
  },
```

![image](https://user-images.githubusercontent.com/7493330/102808566-40259d00-439f-11eb-8522-69ed8f545862.png)
